FILESYSTEM = {
    "/": {"type": "directory", "children": ["home", "etc", "logs", "missions", "NEXUS"]},
    "/home": {"type": "directory", "children": ["nexus"]},
    "/home/nexus": {"type": "directory", "children": ["readme.txt", "notes.txt"]},
    "/home/nexus/readme.txt": {"type": "file", "content": "Welcome to NEXUS OS.\n\nIf you are reading this, the node is awake.\n\nCheck your messages before you trust the desktop."},
    "/home/nexus/notes.txt": {"type": "file", "content": "Check the system logs.\nSomething doesn't look right.\n\nUseful places:\n/logs\n/etc\n/missions"},
    "/etc": {"type": "directory", "children": ["hostname", "network.conf", "security.conf"]},
    "/etc/hostname": {"type": "file", "content": "NEXUS-NODE-01"},
    "/etc/network.conf": {"type": "file", "content": "interface=eth0\naddress=192.168.1.24\ngateway=192.168.1.1"},
    "/etc/security.conf": {"type": "file", "content": "audit=enabled\nwatcher=nexus-watch\nstarted=03:17\nremote_audit=enabled"},
    "/logs": {"type": "directory", "children": ["system.log", "access.log", "network.log", "startup.log"]},
    "/logs/system.log": {"type": "file", "content": "[03:16:51] REMOTE AUTHENTICATION REQUEST\nSOURCE: 192.168.1.44\nUSERNAME: administrator\nMETHOD: SSH\nSTATUS: FAILED\n\n[03:16:52] administrator FAILED\n[03:16:53] administrator FAILED\n[03:16:54] administrator FAILED\n[03:16:55] administrator FAILED\n\n[03:17:01] SECURITY EVENT DETECTED\n[03:17:02] SYSTEM POLICY UPDATED\n[03:17:04] NEXUS-WATCH INITIALIZED\n[03:17:05] TARGET: 192.168.1.44\n[03:17:06] MONITORING ACTIVE"},
    "/logs/access.log": {"type": "file", "content": "[00:12:41] USER LOGIN\nUSER: operator\nSOURCE: LOCAL\n\n[01:44:12] USER LOGIN\nUSER: operator\nSOURCE: LOCAL\n\n[03:16:51] REMOTE CONNECTION\nSOURCE: 192.168.1.44\nSTATUS: ACCEPTED\n\n[03:17:03] SESSION TERMINATED\nSOURCE: 192.168.1.44\n\n[03:17:04] LOCAL SECURITY SERVICE INITIALIZED"},
    "/logs/network.log": {"type": "file", "content": "[00:14:02] NETWORK SERVICE STARTED\n[00:14:03] INTERFACE: NEXUS\n[00:14:03] ADDRESS: 192.168.1.24\n[00:14:04] GATEWAY: 192.168.1.1\n\n[03:16:42] NETWORK CONNECTION DETECTED\nSOURCE: 192.168.1.44\n[03:16:51] REMOTE CONNECTION ATTEMPT\nSOURCE: 192.168.1.44\n[03:16:56] CONNECTION STATE: ESTABLISHED\n[03:16:57] REMOTE DATA TRANSFER\nSOURCE: 192.168.1.44\nSIZE: 4 KB\n[03:16:58] REMOTE DATA TRANSFER\nSOURCE: 192.168.1.44\nSIZE: 4 KB\n[03:16:59] CONNECTION CLOSED\n\n[03:17:02] NETWORK CONFIGURATION CHANGED\nPREVIOUS ADDRESS: 192.168.1.17\nCURRENT ADDRESS: 192.168.1.24\n\n[03:17:04] NEXUS-WATCH INITIALIZED"},
    "/logs/startup.log": {"type": "file", "content": "[03:02:00] NEXUS SYSTEM BOOT\n[03:02:01] CORE ONLINE\n[03:02:02] NETWORK ONLINE\n[03:02:03] STORAGE ONLINE\n[03:02:04] SECURITY WARNING"},
    "/missions": {"type": "directory", "children": ["mission01", "mission02", "mission03"]},
    "/missions/mission01": {"type": "directory", "children": ["brief.txt"]},
    "/missions/mission01/brief.txt": {"type": "file", "content": "MISSION 01\n\nDetermine what machine you are sitting on and reconstruct the first network trace.\n\nSkills: identity, filesystem navigation, logs, IP addresses."},
    "/missions/mission02": {"type": "directory", "children": ["brief.txt"]},
    "/missions/mission02/brief.txt": {"type": "file", "content": "MISSION 02\n\nInvestigate the watcher, the failed authentication, and the missing six seconds.\n\nSkills: processes, connections, timelines, file evidence."},
    "/missions/mission03": {"type": "directory", "children": ["brief.txt"]},
    "/missions/mission03/brief.txt": {"type": "file", "content": "MISSION 03\n\nDetermine what NEXUS was trying to recover and why the watcher was changed.\n\nSkills: configuration analysis, process correlation, incident reconstruction."},
    "/NEXUS": {"type": "directory", "children": ["services", "temp", "archive"]},
    "/NEXUS/services": {"type": "directory", "children": ["nexus-core.exe", "nexus-ui.exe"]},
    "/NEXUS/temp": {"type": "directory", "children": []},
    "/NEXUS/archive": {"type": "directory", "children": []},
    "/NEXUS/services/nexus-core.exe": {"type": "file", "content": "NEXUS CORE SERVICE"},
    "/NEXUS/services/nexus-ui.exe": {"type": "file", "content": "NEXUS UI SERVICE"},
}
